xpsi/module_generator.py

The bug in #27 turned out to be more of an unintuitive approach than a bug, leading to human errors. It was previously unclear when filing the configuration file that the count matrix path has to be necessarily provided, even if there is none. The original reason for this was that the `exception` block then generated the counts matrix file and saved it to that path, so that in later run iterations, it is used instead, thus saving computation time. 
The new workaround doesn't require a count matrix path to be necessarily provided, and saves the count matrix generated from the event file into a new file sharing the same path as the event file, and shares the same name with an added `'_converted_to_counts.txt'` to the filename. An output is also generated for the user to update the …

Additions to #28. Saves count matrix file if input only takes event file

---

xpsi/Signal.py

Raises an error if data.channels and instrument.channels[a:b] do not have the same length; to avoid a cryptic error (see #20)

Bug fix for Issue #20

---

docs/source/contributing.rst
docs/source/intro.txt

Changes to Introductory page and Contributing pages to reflect change of main branch name from master -> main.
Fixes issue #61

Changed master to main in documentation

---

docs/source/install.rst
xpsi/Spacetime.py
xpsi/tests/test_spacetime.py

This patch contains a new script `test_spacetime.py` in a new folder `tests` within the XPSI code folder. This contains tests for the `Spacetime` class, using the pytest package for testing. I've also added a line to the docs to mention that for running the tests, the pytest package is required. 
Once these tests are merged, I can start working on getting the automated testing infrastructure to work :)

Tests for Spacetime class

---

README.rst
docs/source/Instrument_synergy.ipynb
docs/source/Modeling.ipynb
docs/source/Start_here.rst
docs/source/Surface_radiation_field_tools.ipynb
docs/source/applications.rst

Corrects Zenodo link for auxiliary tutorial files to most up-to-date version (close issue #166)
Adds link to Salmi et al. 2022 in Applications (close issue #169 )

Links to updated publications and Zenodos

---

docs/source/HPC_systems.rst
docs/source/install.rst

Added the line about setting the environment variable for the library path to point to Multinest, which was previously on the HPC instructions page, to the main installation page.
Corrected some minor typos. 
Addresses issue #187

Minor corrections to installation documentation

---

joss/paper.md

Correct JOSS paper license information to GNU GPL.
Solves #195

Correct license info in JOSS paper

---

setup.py

I added a `noopenmp` option in the `setup.py` that will remove the `fopenmp` compilation arguments.
@drannawatts, could you give it a try ?

Noopenmp install option

---

docs/source/Instrument_synergy.ipynb
docs/source/Modeling.ipynb
examples/examples_fast/Modules/CustomInstrument.py
examples/examples_fast/Modules/main.py
examples/examples_modeling_tutorial/TestRun_BB.py
examples/examples_modeling_tutorial/TestRun_Num.py
examples/examples_modeling_tutorial/TestRun_NumBeam.py

All examples and notebooks need `channel_edges` to be a mandatory argument

Make mandatory channel_edges argument in CustomInstrument

---

docs/source/intro.rst

I forgot to update the link in the Python2 version of the warning to point to the Python3 docs. Oops!

Fixed link in intro page

---

CHANGELOG.rst
docs/source/FAQ.rst
docs/source/acknowledgements.rst
docs/source/applications.rst
docs/source/citation.rst
docs/source/install.rst
docs/source/todo.rst

Updates to Citation, Team & Acknowledgements, Applications pages.
Update to Future page (for py2, to point out that it has none).
Note:  will break some cross-references to papers (R19, R21 references) in the py2 documentation.  Not fatal but may fix this at a later date.

General py2 documents update

---

.github/workflows/build_docs.yml

Fixes #201 in a slightly hacky way by compiling both the Python2 and Python3 documentation by hand. But it works. :)

Multiversion docs but by hand

---

.github/workflows/build_docs.yml

The python2 branch has all the relevant changes, so we should use that one to build docs.

Use python2 branch to compile docs

---

xpsi/Data.py

that one must have fallen through the cracks of py2 -> py3

`np.int` changed to `np.int32`

---

docs/source/HPC_systems.rst

from 
3.20.1-GCCcore-10.3.0 
to
3.23.1-GCCcore-11.3.0

Fix 1 line for instructions to install on Snellius

---

CHANGELOG.rst
xpsi/PostProcessing/_runs.py

Fixed a bug when combining multiple runs in ``xpsi/PostProcessing/_runs.py``, which caused the combination sometimes fail since PolyChord (instead of MultiNest) default was used for the initial live point likelihoods in dead-birth files. This bug appeared after switching to use a non-customized version of NestCheck (after X-PSI version 2.0.0). Now the newest NestCheck version allows to change this value, and this change is now done within X-PSI. If trying to use an older NestCheck version, an error is raised.

Fix to combining multiple runs.

---

docs/source/Example_job.rst
docs/source/HPC_systems.rst

Removed spaces before and after "~=" when conda installing `cython~=0.29` (otherwise it does not work).
I also changed the module loading order in the HPC example jobs to match that used when installing X-PSI and for Helios loading now the openmpi module **before** installing mpi4py (and before activating x-psi environment) as suggested previously by Martin.

Installation and script fixes

---

CHANGELOG.rst
xpsi/PostProcessing/_corner.py

Preventing the prior probability values from being exactly zero (or negative) for KL-divergence calculation to prevent infinite values for the log-probabilities.

Numerical fix in KL-divergence calculation

---

.github/workflows/ci_tests.yml

Fixed here the `flake8` issue by correcting python version setting when creating conda environment with micromamba. Apparently, we have so far in practice always used the newest python version for all the CI-tests, even though trying to do it separately for 3.8, 3.9, 3.10, and 3.11. And now when the newest version is 3.12, all the tests failed because the `flake8 `package seems broken for that version (at least I could not install it without getting an inconsistent version for the needed `importlib-metadata` package as mentioned in the issue #340). 
I fixed the conda environment creation to actually use the intended python versions and also switched from the deprecated `provision-with-micromamba` method to the `setup-micromamba` method as explained …

Fix to failing continuous integration GitHub Actions

---

xpsi/PostProcessing/_corner.py

`np.float` was a deprecated alias for the builtin `float`. The aliases was originally deprecated in NumPy 1.20.

Corrected deprecated version of numpy float

---

docs/source/FAQ.rst
docs/source/HPC_systems.rst
docs/source/Modeling_without_statistics.ipynb
xpsi/Photosphere.py

HPC installation instructions have been updated to use the latest mpi4py version (3.1.5) when downloading it from the source. The previous ones do not work with the newest Python version (3.12). Some other small fixes to the instructions were done too. Fixed also some typos in the documentation and a bug in the code creating sky maps.

Small typos, bugs, and HPC installation fixes

---

docs/source/acknowledgements.rst
docs/source/applications.rst

Noticed that the NEoST publication format was a lot neater and better now that we have so many papers, so modified the X-PSI one to match.
Corrected atat error on team page. Don't push when ill.

Changed format of publications, corrected atat error

---

xpsi/utilities/ProjectionTool.py

Bug in the projection tool for PDT-U model fixed (the components of the secondary region were not shown). In addition, the font type of the units was changed from italic to roman. Here a figure before the update
and here the same figure after the update:
I also checked that the code still works correctly for ST-U.

PDT-U projection tool bug fixed and units set to roman font.

---

docs/source/Example_job.rst
docs/source/HPC_systems.rst
docs/source/acknowledgements.rst

Snellius installation instructions (and the example job script) update based on the recommendations and tests from Satish Kamath and @Basdorsman (to improve the performance).
Changes summarized:
- Using foss instead of intel
- Using python virtual environment (if wanted) instead of conda
- A few flags changed when installing MultiNest

Snellius instructions updated

---

examples/examples_fast/Modules/CustomPrior.py
examples/examples_fast/Synthetic_data.ipynb
examples/examples_modeling_tutorial/TestRun_BB.py
examples/examples_modeling_tutorial/TestRun_Num.py
examples/examples_modeling_tutorial/TestRun_NumBeam.py
examples/examples_modeling_tutorial/TestRun_Pol.py
examples/examples_modeling_tutorial/TestRun_PolNum_split_1spot.py
examples/examples_modeling_tutorial/TestRun_PolNum_split_inference.py

X-PSI example scripts udpated to allow same compactness as commonly allowed for NICER analyses and the commonly used multiple imaging restrictions added.
In addition, a comment added to Synthesise notebook on how to save synthetic data without noise if interested (rounding the numbers to nearest integer in this example).

Example script updates

---

xpsi/PostProcessing/_pulse.py
xpsi/PostProcessing/_residual.py
xpsi/PostProcessing/_spectrum.py

The lower limit for the channels in signal plots was set to 0.001 instead of 0, to avoid only showing the channel 0 when it is included and logarithmic scale is used. 
However, I see now that the original behaviour of the code was not in principle wrong. Using a logarithmic scale is just a bad choice if including channel 0 (it makes zeroth bin infinitely large). Do you think this change is still worth doing? 
Attached is an example of the pulse plot including channel 0, using the old code  (only the counts from channel 0 are visible the middle bottom panel).
and here using the new code:

Avoid taking log of 0 when channel 0 is included.

---

.github/workflows/build_docs.yml
README.rst
docs/source/intro.rst

Removed what I think are all of the now irrelevant commands from the build_docs action, have also cross-checked with the neost build_docs action.
One question - should we upgrade micromambav1 to v2? But not sure what this would do.

Remove py2 documentation from build docs action

---

xpsi/PostProcessing/_corner.py
xpsi/PostProcessing/_metadata.py
xpsi/PostProcessing/_runs.py

Following Basdorsman's suggestion in issue #393, we develop here a new structure that allows to choose each precision for the parameters loaded from the runs and showed in the corner plots. We extended the Runs tool so it can assign chosen precisions for the parameters, using a distribution of integers and/or None objects, which, in the latter case makes the corner plots to choose the original default precision for the involved parameters.

Precisions for parameters in corner plots

---

examples/examples_module_generator/_auto_modules/main.py
xpsi/module_generator.py

default arg changed to `None` in accordance with the deafult arg for `image_order_limit` in `HotRegion`

default arg changed to `None`

---

docs/source/Hot_region_complexity.ipynb
docs/source/Surface_radiation_field_tools.ipynb
docs/source/old/Multiple_imaging.ipynb
examples/examples_fast/Modules/main.py
examples/examples_fast/Sampling.ipynb
xpsi/HotRegion.py
xpsi/Parameter.py
xpsi/tests/test_hotregion.py
xpsi/tests/test_hotregions.py
xpsi/tests/test_likelihood.py

Here I added basic run, getter and setter tests for all functions in hotregion.py
However, not every reasonable model configuration has been tested. For example, I am not testing ceding and omitting hot spots and numerical atmospheres yet. Best would be to also add some asserts to ensure that the correct values come out. Still, the tests we have so far can be checked and merged in my opinion.
Here I also deprecate the `is_secondary` keyword argument in the HotRegion class. So if this issue is closed that other issue can also be closed.

254 unit tests for hotregion

---

.github/ISSUE_TEMPLATE/feature_request.md
LICENSE
docs/source/conf.py

Update copyright years and remove Tom as default assignee for features!

Update years and stop assigning all tasks to Tom by default

---

xpsi/Signal.py

Closes #491 
Corrected the bug originating from the deepcopy in the `Signal.py` 
I have no run on hand with this derive setup, can anyone check this actually fixes the bug ?

Corrected deepcopy bug on instrument and data

---

examples/examples_modeling_tutorial/TestRun_BB.py
examples/examples_modeling_tutorial/TestRun_Num.py
examples/examples_modeling_tutorial/TestRun_NumBeam.py

Example scripts in `examples_modeling_tutorial` folder were updated to pass the likelihood checks using the new synthetic data. In case of `TestRun_BB.py` I updated the model and instrument response methods to match those of the actual Modeling tutorial notebook in the documentation pages. In the other examples, I just updated the likelihood values and added a comment that the model (and the response files) used in those examples are not the same as used when generating the data (which was the case already before anyway, since they are using a numerical atmosphere).

Example scripts fixed

---

docs/source/FAQ.rst

As discussed during the hack week, I added information about the import order issue of numpy and pymultinest to the FAQ pages so that the GitHub issue can be closed. 
I also tried to reproduce the issue with newer X-PSI installations (both X-PSI v3.0.0 and v1.2.1 with newest dependencies), but I was not able to do that. Instead, the import order did not seem to affect the results at all (which I think makes more sense). I mentioned this also in the FAQ. I could not either reproduce the issue with the exact packages that were reported in the original issue, since my current laptop does not have an old enough version of gcc.

Import order issue moved to FAQ.

---

.github/workflows/build_docs.yml
.github/workflows/ci_tests.yml

As discussed in https://github.com/xpsi-group/xpsi/pull/506, newer gcc version is needed for the GitHub Action workflows when installing X-PSI, because the latest default Ubuntu version has upgraded and has no gcc-10 anymore.

Updating GitHub workflows to use newer gcc

---

.github/workflows/build_docs.yml
.github/workflows/ci_tests.yml

* Change to gcc-12 for CI tests
* Do testing also with Py3.12
* Use gcc-12 in build_docs

Merging the updated main branch to the accretion disk tutorial branch

---

docs/source/HPC_systems.rst

Typos fixed in HPC installation instructions and mpi4py installation instruction added for Snellius.

HPC doc fixes

---

xpsi/PostProcessing/_backends.py
xpsi/PostProcessing/_nestcheck_modifications.py
xpsi/PostProcessing/_run.py

To post-process the data, you can now also use .npy files, which is (a lot) faster than .txt files. Additionally, I changed the structure of the `PostProcessing/_backends.py` to increase readability, and to ensure that each file only gets loaded once (instead of multiple times as before). The latter is also the reason why we now have our own modified `process_multinest_run()` in `._nestcheck_modifications` instead of loading it from `nestcheck.data_processing` itself.

523 speed up post processing

---

examples/examples_modeling_tutorial/TestRun_Num.py
examples/examples_modeling_tutorial/TestRun_NumBeam.py
xpsi/Photosphere.py

Added a few checks before starting photosphere integration that the given parameters are within atmosphere table limits. Currently, this assumes the atmosphere table has the nsx format. But it is possible to customize this. I guess only issue is that this check needs to be done on every pulse profile computation. The reason is that we do not know in advance whether the surface gravity for the sampled mass and radius will be within the atmosphere bounds. Similar check is also done typically in the call-function of CustomPrior, but the check here can be an additional safety measure since it does not require user to manually set the surface gravity limits. Or if we modify the standard CustomPrior to also automatically obtain the surface gravity limits, then the checks here may become not …

Checking that T and logg within atmosphere bounds if using nsx

---

docs/source/changelog_docs.rst
docs/source/history.rst

Fixing the broken History/Changelog appearance in the documentation pages (to not show all the subtitles in the side bar).

Fixing Changelog appearance in docs

---

xpsi/cellmesh/integrator.pyx
xpsi/cellmesh/integratorIQU.pyx
xpsi/cellmesh/integratorIQU_for_azimuthal_invariance.pyx
xpsi/cellmesh/integratorIQU_for_azimuthal_invariance_split.pyx
xpsi/cellmesh/integrator_for_azimuthal_invariance.pyx
xpsi/cellmesh/integrator_for_azimuthal_invariance_split.pyx
xpsi/cellmesh/integrator_for_time_invariance.pyx
xpsi/cellmesh/mesh.pyx
xpsi/cellmesh/mesh_tools.pyx
xpsi/cellmesh/polar_mesh.pyx
xpsi/cellmesh/rays.pyx
xpsi/likelihoods/_gaussian_likelihood_given_background_IQU.pyx
xpsi/likelihoods/_poisson_likelihood_given_background.pyx
xpsi/likelihoods/_poisson_likelihood_given_background_IQU.pyx
xpsi/likelihoods/default_background_marginalisation.pyx
xpsi/pixelmesh/RODES_qK.pyx
xpsi/pixelmesh/globalRayMap.pyx
xpsi/surface_radiation_field/hot_wrapper.pyx
xpsi/tools/core.pxd
xpsi/tools/core.pyx

All the double == double comparisons that I found (at least in the Cython codes) were replaced with `are_equal()` function that I placed in `tools/core.pyx` and that allows 1e-12 tolerance (by default) around the exact value.
I tested a couple of the test example runs, that they give still the same results as before.

Cython double==double comparisons made approximate

---

changelog.d/605.attribution.rst
changelog.d/605.fixed.rst
examples/examples_modeling_tutorial/TestRun_Num.py
examples/examples_modeling_tutorial/TestRun_NumBeam.py

The additional checks making sure that atmosphere table bounds are not exceeded are causing the TestRun_Num.py and TestRun_NumBeam.py fail with an error message. So far this issue was not noticed because going beoynd limits was not prevented.

Numerical atmos test runs fixed to not go beyond atmosphere table limits.

---

docs/source/applications.rst

Adding the eXTP white paper to publications list (putting simulations papers in the 'General PPM studies' section of the publications list).

Adding eXTP white paper to publications list
