xpsi-group/xpsi

- CHANGELOG.md
- setup.py
- xpsi/__init__.py
- xpsi/surface_radiation_field/archive/elsewhere/numerical.pyx
> Thomas edward riley patch 1

- docs/source/install.rst
- setup.py
Addressing issue #72:
Adding optional flags to copy the contents of /hot/numerical.pyx or /elsewhere/numerical.pyx, in order to compile XPSI with numerical atmosphere.
> Updating setup.py

- docs/source/install.rst
> Sphinx installation instructions for python2 added to `install.rst`

- xpsi/ParameterSubspace.py
> Parameter not present in subspace indicated in error message displayed

- docs/source/model_construction_streamlined.ipynb
- docs/source/multiple_instruments.ipynb
- docs/source/spacetime.rst
- xpsi/Spacetime.py
* removing fixed_spin 
* modification of the tutorial notebook mentioning fixed_spin
> fixed_spin method deleted from Spacetime class

- xpsi/tests/test_instrument.py
> unit tests for Instrument class

- .github/workflows/ci_tests.yml
- examples/examples_fast/Modules/CustomPhotosphere.py
Second attempt at a pull request for Github Actions to automatically run continuous integration tests with pytest.
> Added script for CI tests

- basic_environment.yml
- docs/source/install.rst
> Install page updated

- xpsi/PostProcessing/_postprocessor.py
> Limitation on number of plots set to 9 due to prevent plot overcrowding.

- docs/source/install.rst
> Duplicate section, bashrc & profile examples removed. Mac comms refined

- README.rst
Test PR to see if it triggers CI. Also adds some sweet badges to the README
> Added badges to readme

- joss/paper.md
This might fix the JOSS compilation.
> Fixed Orcid for Serena

- .github/workflows/build_docs.yml
- .github/workflows/ci_tests.yml
- .github/workflows/joss.yml
- docs/source/intro.txt
... so that you don't need to do this manually. Not sure it's working yet.
> Build docs via GitHub Actions

- COPYING
- LICENSE
- README.rst
Addresses issue raised by JOSS reviewers on appropriateness of licence, will close issue #184
> Updated licence file, 

- setup.py
Updated lience information and development status in the setup.py file
> Updated licence info and development status in setup.py file

- .github/workflows/build_docs.yml
- .github/workflows/ci_tests.yml
- xpsi/utilities/ImportanceSample.py
- xpsi/utilities/ProjectionTool.py
Linter threw some errors in the ProjectionTool and ImportanceSampling steps. This attempts to fix them.
Follows on from #209, which fails because of the linter. This PR includes the same changes to the GitHub Actions
> Fixing Py3 linting issues

- xpsi/pixelmesh/globalRayMap.pyx
- xpsi/pixelmesh/integrator.pyx
This is only for the tutorial notebooks, not the inference runs.
But makes things cleaner
> Suppressed printf() statements from c code

- docs/source/Instrument_synergy.ipynb
- `ax.plot` with `ls='steps'` argument replaced by `ax.step`
- Shifting the phase bins by half a bin width to be compatible with recent pcolormesh requirements.
- Additional text for explanation
> Changes in Instrument synergy tutorial notebook

- .github/workflows/build_docs.yml
Following Johannes Buchner's suggestion, trying to speed up GH Actions.
> Moving conda install commands to one line to speed up build

- xpsi/utilities/ProjectionTool.py
> 234 debugging projection tool

- .github/workflows/build_docs.yml
- .github/workflows/ci_tests.yml
Updating Github Actions to make them faster.
> Update GitHub Actions

- xpsi/PostProcessing/_corner.py
The outputs are here. 
[Postprocessing.pdf](https://github.com/xpsi-group/xpsi/files/10569077/Postprocessing.pdf)
> Adding names of parameters across diagonal in corner plots

- docs/source/index.rst
- docs/source/intro.rst
this is a PR for the python2 version of the code, to add a warning to the docs.
> Added warning to front page of docs

- CHANGELOG.rst
- docs/source/FAQ.rst
- docs/source/acknowledgements.rst
- docs/source/applications.rst
- docs/source/citation.rst
- docs/source/index.rst
- docs/source/install.rst
- docs/source/intro.rst
- joss/paper.md
I think this should merge Anna's changes in the docs into the python3 branch, if I did everything correctly.
> Merging python2 docs

- CHANGELOG.rst
Devarshi and Sebastien have already made some additions/changes to this. Would be good if everyone can check this though to make sure their changes are properly listed somewhere!
Addresses #226
> Changelog for v2

- xpsi/utilities/ProjectionTool.py
only changes should be fixes of (many) typos (and a few re-phrases) in ProjectionTool.py and Emitting_patterns_2Dprojection.ipynb
> 264 fixing typos in tutorial for projection tool

- joss/xpsijoss.bib
Added missing DOI flagged by the JOSS Editorialbot
> Added DOI to JOSS bib file

- joss/paper.md
- joss/xpsijoss.bib
First updating the JOSS paper on the main branch, can you double check that I have addressed all of the final comments from the Editor? 
Once this is on the main branch and I've checked that it looks OK using JOSS Editorialbot I'll do a separate pull request of the same files for the py2 branch for the tagged release.
> Updates to JOSS paper on main branch

- joss/paper.md
- joss/xpsijoss.bib
So now the same JOSS files updates, but this time to the py2 branch....
> JOSS paper updates to py2

- docs/source/HPC_systems.rst
- docs/source/install.rst
> Python2 installation update

- docs/source/citation.rst
Updated citation page for published version of JOSS paper, and added link.
> Adding publication details for JOSS paper

- docs/source/Hot_region_complexity.ipynb
- docs/source/Modeling_without_statistics.ipynb
- docs/source/Start_here.rst
- docs/source/applications.rst
Fixing the mentions of units for flux in tutorials, the linking of new tutorials in the landing page, and updating the application page for new publications.
> Documentation updates

- basic_environment.yml
- docs/source/HPC_systems.rst
- docs/source/install.rst
- environment.yml
- setup.py
in environment yml files, and in installation documentation.
> requirements for cython version

- .github/workflows/ci_tests.yml
- CHANGELOG.rst
- xpsi/PostProcessing/_signalplot.py
Extra ticks options added as suggested in the issue #243 . The post-processing tutorial has been updated to show how to use these options.
> Extra ticks options for the 2d pulse plots in the post processing

- docs/source/applications.rst
Added links to Salmi et al. 2023, Vinciguerra et al. 2023, 2024, Kini et al. 2024.
> Updates to publications list

- docs/source/acknowledgements.rst
- docs/source/applications.rst
Updates to a couple of now published paper to give the ADS link.
Added Mariska to core team list.
> Small updates to team and published papers

- docs/source/applications.rst
Updates to add the latest papers.  Can maybe be merged with upcoming elsewhere fix pull request?
> Updates to publication list

- docs/source/applications.rst
Linked to published version of J0437 paper.
> Updating PSR J0437 publication link

- .github/workflows/build_docs.yml
- .github/workflows/joss.yml
I think this mimics the changes that were made to the NEoST actions a few weeks ago - but the actions have other differences so possible we break something else.
> Fix build_docs and JOSS actions

- basic_environment.yml
- docs/source/install.rst
Update Post-processing legend regarding to recent Matplotlib versions.
> Post-processing update

- docs/source/HPC_systems.rst
- docs/source/citation.rst
- docs/source/install.rst
- docs/source/sample.rst
- xpsi/Sample.py
- xpsi/UltranestSampler.py
Please check if you can install ultranest in your current environment and run the tutorial/if it makes sense
> 399 ultranest documentation

- docs/source/acknowledgements.rst
- docs/source/todo.rst
> Updating future plans file and Dutchifying Lucien's name

- docs/source/Modeling_without_statistics.ipynb
- docs/source/acknowledgements.rst
- docs/source/applications.rst
Partially addresses #450 (makes corrections from proofreading).
Still need to re-run tutorials before issue is fully closed.
> Small corrections to various pages

- xpsi/Everywhere.py
- xpsi/likelihoods/default_background_marginalisation.pyx
phases and leaves forced to 1 in Everywhere if `time_invariant=True` and interpolation initialization skipped if phases/leaves are 1
> Everywhere with time_invariant=True, phases and leaves forced to 1

- docs/source/applications.rst
Modified publications page in documentation to add the new papers by Bootsma et al. (scaling), Salmi et al. (polarimetry) and Dorsman et al. (AMXPs)
> Publications update

- xpsi/Instrument.py
> Made warning and error messages in Instrument more explicit

- xpsi/module_generator.py
This module-generator script includes potential structures for modules if the observational data are stored into fits files.
> 551-choice-of-customization-inside-module-generator

- docs/source/extension_modules.rst
- docs/source/index.rst
- docs/source/likelihood_api.rst
- docs/source/posterior_api.rst
Addresses Issue #541  by tidying up the APIs a bit (they are still in three classes since I feel like this it's slightly useful to keep the likelihood ones separate?).  But maybe others feel differently!
> Consolidating the API

- docs/source/HPC_systems.rst
> mpiexec pymultinest demo in hpc systems

- xpsi/Data.py
> modification of data plotting function

- changelog.d/591.attribution.rst
- changelog.d/591.fixed.rst
- xpsi/PostProcessing/_backends.py
- xpsi/PostProcessing/_nestcheck_modifications.py
Nestcheck=True broke the post-processing, this is now fixed. The .stats file is removed from the loading runs, since these output files are not used anymore.
> 570 nestchecktrue

- xpsi/tests/test_postprocessing.py
Updated the new post-processing GitHub tests to use the new module loader
> Postprocessing test updated with module loader

- docs/source/Example_job.rst
- docs/source/HPC_systems.rst
I updated the suggested partition name for the Snellius example script, and added a couple of python packages (usually/often needed) to the Snellius installation instructions.
> Snellius instructions updated
